### ISSUE TITLE
Clean asibot-main libraries

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/asibot-main#28]
There are a number of libraries that should go elsewhere or become deprecated in favor of advances. This is not mandatory, but we have been working a lot elsewhere
- [x] CartesianClientLib. (see cartesianServer on #21). ELIMINATE :skull_and_crossbones:
- [x] CartesianServerLib. (see cartesianServer on #21). ELIMINATE :skull_and_crossbones:
- [x] ColorClientLib. I'd replace it by an issue on the final vision-related repository mentioning that a API for all vision libs with a nice server/client pair would be nice. ELIMINATE :skull_and_crossbones:
- [x] RavePlugins. Can improve (not only redCan) and move to [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins). :smile::truck: (roboticslab-uc3m/openrave-yarp-plugins#26)
- RlPlugins
  - [x] cartesianbot. Can be made into a plugin similar to KdlSolver. GOOD TO KEEP :smile::truck: because it has the ASIBOT analytic solution of FK and IK (as far as I recall). kinematics (roboticslab-uc3m/kinematics-dynamics#96)
  - [x] kdlbot. (see cartesianServer on #21). ELIMINATE :skull_and_crossbones:
  - [x] ravebot. Work in progress is to use [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins)  with separate model repos similar to [teo-openrave-models](https://github.com/roboticslab-uc3m/teo-openrave-models) to substitute testRaveBot and also teoSim of teo-main. For now only joint movements are implemented, but plugins for creating objects, publishing sensor data etc are on the way. GOOD TO KEEP :smile::minibus: (roboticslab-uc3m/openrave-yarp-plugins#26)
  - [x] skymegabot: Was used to send commands to an Arduino connected to a Hand controlled by PWM. Many copies in many places. A pretty functional yarp plugin is [LaserTowerOfDeathController](https://github.com/asrob-uc3m/robotDevastation-robots/tree/develop/libraries/YarpPlugins/LaserTowerOfDeathController). ELIMINATE :skull_and_crossbones:
- [x] TestRaveBotLib: Same as ravebot and testRaveBot. GOOD TO KEEP :smile::minibus: (roboticslab-uc3m/openrave-yarp-plugins#26)
- [x] TinyMath: It's a nice thing to have around when you already depend on YARP, don't want to thing about KDL, and want to play around with transformation matrices. Uses YARP_math for operators and eye(). Possibly used by several programs, which should be identified. GOOD TO KEEP :smile::truck: kinematics (roboticslab-uc3m/kinematics-dynamics#96)
- [x] TrajGen: Interesting experimental class for trajectories that does not depend on KDL, seems to be used by cartesianbot. GOOD TO KEEP :smile::truck: (to be moved together with cartesianbot). kinematics (roboticslab-uc3m/kinematics-dynamics#96)
- [x] TaskLib: An idea is to migrate these demo-like behaviours to an interpreted language. GOOD TO KEEP :smile: tools

**Comment by PeterBowman** [comment]
Note: TinyMath is still called by TaskLib.

**Comment by jgvictores** [comment]
`ravebot` was never actually migrated, but I'd say that with https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/38, it is definitely superseeded by YarpOpenraveControlboard.

**Comment by jgvictores** [comment]
Well, maybe not completely superseeded until https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/29 and https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/39 are done.

**Comment by jgvictores** [comment]
https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/29 is now closed, `YarpOpenraveControlboard` is an efficient re-implementation of `ravebot`.

As for https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/39, it just provides a couple of checks and parameters, will be soon closed.

**Comment by jgvictores** [comment]
Marking `TaskLib` too (which was the only lib missing), of which progress will be tracked at #40.

Closing issue!
